const NEW_CLIENT = " NEW_CLIENT";
const ALL_CLIENTS = "ALL_CLIENTS";
const GET_CLIENT_BY_ID = "GET_CLIENT_BY_ID";
const CLIENT_UPDATE = "CLIENT_UPDATE";
const NEW_SUPPLIER = " NEW_SUPPLIER";
const ALL_SUPPLIER = "ALL_SUPPLIER";
const GET_SUPPLIER_BY_ID = "GET_SUPPLIER_BY_ID";
const SUPPLIER_UPDATE = "SUPPLIER_UPDATE";
const CREATE_PRODUCT = 'CREATE_PRODUCT';
const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
const ALL_PRODUCTS = 'ALL_PRODUCTS';
const ALL_CHEQUES = 'ALL_CHEQUES';
const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';
const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
const DELETE_PRODUCT = 'DELETE_PRODUCT';
const CREATE_ORDER = 'CREATE_ORDER';
const EDIT_ORDER = "EDIT_ORDER";
const GET_ORDER_BY_ID = "GET_ORDER_BY_ID";
const DELETE_ORDER = 'DELETE_ORDER';
const CREATE_VEHICLE = 'CREATE_ORDER';
const ALL_ORDERS= "ALL_ORDERS";
const ALL_CASHMOVEMENTS="ALL_CASHMOVEMENTS"
const ALL_BUDGETS="ALL_BUDGETS";
const ALL_BILLS="ALL_BILLS";
const ALL_VEHICLES="ALL_VEHICLE";
const ALL_SHOPPINGS="ALL_SHOPPINGS";
const ALL_SALES="ALL_SALES";
const EDIT_VEHICLE = "EDIT_ORDER";
const GET_VEHICLE_BY_ID = "GET_ORDER_BY_ID";
const DELETE_VEHICLE = 'DELETE_ORDER';






export {
    NEW_CLIENT,
    ALL_CLIENTS, 
    GET_CLIENT_BY_ID,
    CLIENT_UPDATE,
    NEW_SUPPLIER,
    ALL_SUPPLIER, 
    GET_SUPPLIER_BY_ID,
    SUPPLIER_UPDATE, 
    CREATE_PRODUCT, 
    UPDATE_PRODUCT, 
    ALL_PRODUCTS,
    ALL_CHEQUES,
    GET_PRODUCT_BY_ID, 
    SEARCH_PRODUCTS, 
    DELETE_PRODUCT, 
    CREATE_ORDER, 
    ALL_ORDERS, 
    ALL_BUDGETS,
    ALL_BILLS,
    ALL_VEHICLES,
    ALL_SHOPPINGS,
    ALL_SALES,
    ALL_CASHMOVEMENTS,
    EDIT_ORDER,
    GET_ORDER_BY_ID, 
    DELETE_ORDER, 
    CREATE_VEHICLE, 
    EDIT_VEHICLE,
    GET_VEHICLE_BY_ID,
    DELETE_VEHICLE,
    

}
